import '../imports/ui/home'
import '../imports/ui/adminPage'
import '../imports/ui/contact'
import '../imports/ui/blogPage'
import '../imports/ui/about'
import '../imports/ui/editPage'
import '../imports/ui/allPosts'
